-- VALHALLA 0.3 · PostgreSQL / Supabase. Importes en centavos; stock en milésimas.

-- Ejecutar 01, 02, 03 en ese orden; INSTALAR_VALHALLA.sql los reúne en una transacción.

CREATE SCHEMA IF NOT EXISTS valhalla_private;

REVOKE ALL ON SCHEMA valhalla_private FROM PUBLIC, anon, authenticated;

SET LOCAL search_path = valhalla_private, pg_catalog;

CREATE TABLE servicio (
  id_servicio bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  categoria TEXT,
  elegible_fidelidad bigint NOT NULL CHECK (elegible_fidelidad IN (0,1)),
  elegible_cumpleanos bigint NOT NULL CHECK (elegible_cumpleanos IN (0,1)),
  activo bigint NOT NULL CHECK (activo IN (0,1)),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE servicio ENABLE ROW LEVEL SECURITY;

CREATE TABLE cuadre_caja (
  id_cuadre_caja bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sucursal bigint NOT NULL,
  id_cerrado_por bigint NOT NULL,
  idempotency_key TEXT NOT NULL UNIQUE,
  periodo_inicio timestamptz NOT NULL,
  periodo_fin timestamptz NOT NULL CHECK (periodo_fin >= periodo_inicio),
  efectivo_esperado bigint NOT NULL,
  efectivo_contado bigint NOT NULL,
  diferencia bigint NOT NULL,
  explicacion_diferencia TEXT,
  estado TEXT NOT NULL,
  fecha_hora_cierre timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (efectivo_contado >= 0),
  CHECK (diferencia = 0 OR length(trim(COALESCE(explicacion_diferencia,''))) > 0),
  CHECK (diferencia = efectivo_contado - efectivo_esperado)
);

ALTER TABLE cuadre_caja ENABLE ROW LEVEL SECURITY;

CREATE TABLE servicio_precio_historial (
  id_servicio_precio bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_servicio bigint NOT NULL,
  precio bigint NOT NULL CHECK (precio >= 0),
  vigencia_desde timestamptz NOT NULL,
  vigencia_hasta timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE servicio_precio_historial ENABLE ROW LEVEL SECURITY;

CREATE TABLE rol (
  id_rol bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT NOT NULL UNIQUE,
  nombre TEXT NOT NULL,
  activo bigint NOT NULL CHECK (activo IN (0,1))
);

ALTER TABLE rol ENABLE ROW LEVEL SECURITY;

CREATE TABLE usuario (
  id_usuario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_rol bigint NOT NULL,
  auth_uid uuid UNIQUE REFERENCES auth.users(id) ON DELETE RESTRICT,
  nombre_completo TEXT NOT NULL,
  activo bigint NOT NULL CHECK (activo IN (0,1)),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  correo text NOT NULL UNIQUE CHECK (correo = lower(trim(correo))),
  acceso_desde timestamptz NOT NULL DEFAULT '-infinity'
);

ALTER TABLE usuario ENABLE ROW LEVEL SECURITY;

CREATE TABLE gasto (
  id_gasto bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sucursal bigint NOT NULL,
  id_registrado_por bigint NOT NULL,
  id_metodo_pago bigint NOT NULL,
  id_banco bigint,
  idempotency_key TEXT NOT NULL UNIQUE,
  fecha_hora timestamptz NOT NULL DEFAULT now(),
  categoria TEXT NOT NULL,
  descripcion TEXT NOT NULL,
  monto bigint NOT NULL CHECK (monto > 0),
  observacion TEXT,
  created_at timestamptz NOT NULL DEFAULT now(),
  id_cuadre_caja bigint 
);

ALTER TABLE gasto ENABLE ROW LEVEL SECURITY;

CREATE TABLE cliente (
  id_cliente bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_completo TEXT NOT NULL,
  telefono TEXT NOT NULL,
  fecha_nacimiento date NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE cliente ENABLE ROW LEVEL SECURITY;

CREATE TABLE sucursal (
  id_sucursal bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  activo bigint NOT NULL CHECK (activo IN (0,1)),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE sucursal ENABLE ROW LEVEL SECURITY;

CREATE TABLE cita (
  id_cita bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente bigint NOT NULL,
  id_sucursal bigint NOT NULL,
  id_barbero bigint NOT NULL,
  id_creada_por bigint NOT NULL,
  fecha_hora timestamptz NOT NULL DEFAULT now(),
  estado TEXT NOT NULL,
  observaciones TEXT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  duracion_minutos bigint NOT NULL DEFAULT 30 CHECK(duracion_minutos BETWEEN 5 AND 480),
  id_confirmada_por bigint ,
  confirmada_at timestamptz
);

ALTER TABLE cita ENABLE ROW LEVEL SECURITY;

CREATE TABLE operacion (
  id_operacion bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente bigint NOT NULL,
  id_cita bigint UNIQUE,
  id_sucursal bigint NOT NULL,
  id_barbero bigint,
  id_registrada_por bigint NOT NULL,
  id_cuadre_caja bigint,
  idempotency_key TEXT NOT NULL UNIQUE,
  fecha_hora timestamptz NOT NULL DEFAULT now(),
  estado TEXT NOT NULL,
  total_bruto bigint NOT NULL CHECK (total_bruto >= 0),
  total_descuentos bigint NOT NULL CHECK (total_descuentos >= 0),
  total_cobrado bigint NOT NULL CHECK (total_cobrado >= 0),
  observaciones TEXT,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CHECK (total_cobrado = total_bruto - total_descuentos)
);

ALTER TABLE operacion ENABLE ROW LEVEL SECURITY;

CREATE TABLE regla_comision (
  id_regla_comision bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_servicio bigint,
  nombre TEXT NOT NULL,
  circunstancia TEXT,
  tipo_calculo TEXT NOT NULL,
  valor bigint NOT NULL CHECK (valor >= 0),
  vigencia_desde timestamptz NOT NULL,
  vigencia_hasta timestamptz,
  activo bigint NOT NULL CHECK (activo IN (0,1))
);

ALTER TABLE regla_comision ENABLE ROW LEVEL SECURITY;

CREATE TABLE motivo_gratuidad (
  id_motivo_gratuidad bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT NOT NULL UNIQUE,
  nombre TEXT NOT NULL,
  activo bigint NOT NULL CHECK (activo IN (0,1))
);

ALTER TABLE motivo_gratuidad ENABLE ROW LEVEL SECURITY;

CREATE TABLE operacion_servicio (
  id_operacion_servicio bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_operacion bigint NOT NULL,
  id_servicio bigint NOT NULL,
  id_motivo_gratuidad bigint,
  id_regla_comision bigint,
  id_autorizado_por bigint,
  cantidad bigint NOT NULL CHECK (cantidad > 0) DEFAULT 1,
  precio_normal bigint NOT NULL CHECK (precio_normal >= 0),
  precio_aplicado bigint NOT NULL CHECK (precio_aplicado >= 0),
  motivo_descuento TEXT,
  comentario_descuento TEXT,
  elegible_fidelidad_aplicado bigint NOT NULL CHECK (elegible_fidelidad_aplicado IN (0,1)),
  base_comision bigint NOT NULL CHECK (base_comision >= 0),
  monto_comision bigint NOT NULL CHECK (monto_comision >= 0),
  CHECK (precio_aplicado <= precio_normal),
  CHECK (id_motivo_gratuidad IS NULL OR precio_aplicado = 0),
  CHECK (base_comision = precio_aplicado * cantidad)
);

ALTER TABLE operacion_servicio ENABLE ROW LEVEL SECURITY;

CREATE TABLE inventario_sucursal (
  id_inventario_sucursal bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sucursal bigint NOT NULL,
  id_producto bigint NOT NULL,
  stock_actual bigint NOT NULL,
  stock_minimo bigint NOT NULL CHECK (stock_minimo >= 0),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (id_sucursal, id_producto),
  CHECK (stock_actual >= 0)
);

ALTER TABLE inventario_sucursal ENABLE ROW LEVEL SECURITY;

CREATE TABLE membresia_plan (
  id_plan_membresia bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT NOT NULL UNIQUE,
  nombre TEXT NOT NULL,
  precio bigint NOT NULL CHECK (precio >= 0),
  cantidad_servicios bigint NOT NULL CHECK (cantidad_servicios > 0),
  vigencia_desde timestamptz NOT NULL,
  vigencia_hasta timestamptz,
  activo bigint NOT NULL CHECK (activo IN (0,1)),
  created_at timestamptz NOT NULL DEFAULT now(),
  duracion_dias bigint NOT NULL DEFAULT 30 CHECK (duracion_dias > 0)
);

ALTER TABLE membresia_plan ENABLE ROW LEVEL SECURITY;

CREATE TABLE membresia_plan_servicio (
  id_plan_servicio bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_plan_membresia bigint NOT NULL,
  id_servicio bigint NOT NULL,
  UNIQUE (id_plan_membresia, id_servicio)
);

ALTER TABLE membresia_plan_servicio ENABLE ROW LEVEL SECURITY;

CREATE TABLE movimiento_inventario (
  id_movimiento_inventario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sucursal bigint NOT NULL,
  id_producto bigint NOT NULL,
  id_operacion bigint,
  id_operacion_producto bigint,
  id_gasto bigint,
  id_traslado bigint,
  id_usuario_responsable bigint,
  id_registrado_por bigint NOT NULL,
  tipo_movimiento TEXT NOT NULL,
  cantidad bigint NOT NULL CHECK (cantidad > 0),
  fecha_hora timestamptz NOT NULL DEFAULT now(),
  observacion TEXT
);

ALTER TABLE movimiento_inventario ENABLE ROW LEVEL SECURITY;

CREATE TABLE producto (
  id_producto bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  categoria TEXT,
  unidad_medida TEXT NOT NULL,
  precio_venta_actual bigint,
  activo bigint NOT NULL CHECK (activo IN (0,1)),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE producto ENABLE ROW LEVEL SECURITY;

CREATE TABLE operacion_producto (
  id_operacion_producto bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_operacion bigint NOT NULL,
  id_producto bigint NOT NULL,
  cantidad bigint NOT NULL CHECK (cantidad > 0),
  precio_unitario_aplicado bigint NOT NULL CHECK (precio_unitario_aplicado >= 0),
  total_linea bigint NOT NULL CHECK (total_linea >= 0)
);

ALTER TABLE operacion_producto ENABLE ROW LEVEL SECURITY;

CREATE TABLE traslado_inventario (
  id_traslado bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sucursal_origen bigint NOT NULL,
  id_sucursal_destino bigint NOT NULL,
  id_responsable bigint NOT NULL,
  idempotency_key TEXT NOT NULL UNIQUE,
  fecha_hora timestamptz NOT NULL DEFAULT now(),
  observacion TEXT,
  CHECK (id_sucursal_origen <> id_sucursal_destino)
);

ALTER TABLE traslado_inventario ENABLE ROW LEVEL SECURITY;

CREATE TABLE membresia (
  id_membresia bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente bigint NOT NULL,
  id_plan_membresia bigint NOT NULL,
  id_operacion_compra bigint,
  fecha_compra timestamptz NOT NULL,
  fecha_activacion timestamptz NOT NULL,
  precio_pagado bigint NOT NULL CHECK (precio_pagado >= 0),
  servicios_iniciales bigint NOT NULL CHECK (servicios_iniciales > 0),
  estado TEXT NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  fecha_vencimiento timestamptz,
  nombre_plan_aplicado TEXT
);

ALTER TABLE membresia ENABLE ROW LEVEL SECURITY;

CREATE TABLE membresia_consumo (
  id_membresia_consumo bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_membresia bigint NOT NULL,
  id_operacion_servicio bigint NOT NULL UNIQUE,
  cantidad bigint NOT NULL CHECK (cantidad > 0) DEFAULT 1,
  fecha_consumo timestamptz NOT NULL
);

ALTER TABLE membresia_consumo ENABLE ROW LEVEL SECURITY;

CREATE TABLE cita_servicio (
  id_cita_servicio bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cita bigint NOT NULL,
  id_servicio bigint NOT NULL,
  cantidad bigint NOT NULL CHECK (cantidad > 0) DEFAULT 1,
  observacion TEXT
);

ALTER TABLE cita_servicio ENABLE ROW LEVEL SECURITY;

CREATE TABLE usuario_sucursal (
  id_usuario_sucursal bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario bigint NOT NULL,
  id_sucursal bigint NOT NULL,
  es_principal bigint NOT NULL CHECK (es_principal IN (0,1)),
  activo bigint NOT NULL CHECK (activo IN (0,1)),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (id_usuario, id_sucursal)
);

ALTER TABLE usuario_sucursal ENABLE ROW LEVEL SECURITY;

CREATE TABLE banco (
  id_banco bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT NOT NULL UNIQUE,
  nombre TEXT NOT NULL,
  activo bigint NOT NULL CHECK (activo IN (0,1))
);

ALTER TABLE banco ENABLE ROW LEVEL SECURITY;

CREATE TABLE metodo_pago (
  id_metodo_pago bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo TEXT NOT NULL UNIQUE,
  nombre TEXT NOT NULL,
  activo bigint NOT NULL CHECK (activo IN (0,1))
);

ALTER TABLE metodo_pago ENABLE ROW LEVEL SECURITY;

CREATE TABLE pago (
  id_pago bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_operacion bigint NOT NULL UNIQUE,
  id_metodo_pago bigint NOT NULL,
  id_banco bigint,
  id_registrado_por bigint NOT NULL,
  monto bigint NOT NULL CHECK (monto >= 0),
  efectivo_recibido bigint,
  cambio bigint,
  referencia_transferencia TEXT,
  fecha_hora timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE pago ENABLE ROW LEVEL SECURITY;

CREATE TABLE movimiento_caja (
  id_movimiento_caja bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_sucursal bigint NOT NULL,
  id_pago bigint,
  id_gasto bigint,
  id_cuadre_caja bigint,
  id_usuario bigint NOT NULL,
  tipo_movimiento TEXT NOT NULL,
  monto bigint NOT NULL CHECK (monto > 0),
  fecha_hora timestamptz NOT NULL DEFAULT now(),
  observacion TEXT,
  CHECK (tipo_movimiento IN ('INGRESO','EGRESO')),
  CHECK (id_pago IS NULL OR id_gasto IS NULL)
);

ALTER TABLE movimiento_caja ENABLE ROW LEVEL SECURITY;

CREATE TABLE bitacora_auditoria (
  id_auditoria bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario bigint NOT NULL,
  id_sucursal bigint,
  entidad TEXT NOT NULL,
  id_registro bigint NOT NULL,
  accion TEXT NOT NULL,
  valor_anterior TEXT,
  valor_nuevo TEXT,
  motivo TEXT,
  fecha_hora timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE bitacora_auditoria ENABLE ROW LEVEL SECURITY;

CREATE TABLE cliente_nota (
  id_nota bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente bigint NOT NULL ,
  id_usuario bigint NOT NULL ,
  texto TEXT NOT NULL,
  created_at timestamptz NOT NULL
);

ALTER TABLE cliente_nota ENABLE ROW LEVEL SECURITY;

CREATE TABLE beneficio_cumpleanos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente bigint NOT NULL ,
  anio bigint NOT NULL,
  id_operacion bigint NOT NULL UNIQUE ,
  UNIQUE(id_cliente,anio)
);

ALTER TABLE beneficio_cumpleanos ENABLE ROW LEVEL SECURITY;

CREATE TABLE solicitud_idempotente (
  clave TEXT PRIMARY KEY NOT NULL,
  accion TEXT NOT NULL,
  id_usuario bigint NOT NULL ,
  id_sucursal bigint NOT NULL ,
  solicitud TEXT NOT NULL,
  id_resultado bigint NOT NULL,
  created_at timestamptz NOT NULL
);

ALTER TABLE solicitud_idempotente ENABLE ROW LEVEL SECURITY;

CREATE TABLE membresia_servicio (
  id_membresia bigint NOT NULL ,
  id_servicio bigint NOT NULL ,
  PRIMARY KEY (id_membresia,id_servicio)
);

ALTER TABLE membresia_servicio ENABLE ROW LEVEL SECURITY;

CREATE TABLE configuracion_negocio (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK(id=1),
  nombre TEXT NOT NULL CHECK(length(trim(nombre)) BETWEEN 2 AND 120),
  meta_fidelidad bigint NOT NULL CHECK(meta_fidelidad BETWEEN 1 AND 100),
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

ALTER TABLE configuracion_negocio ENABLE ROW LEVEL SECURITY;

CREATE TABLE fidelidad_movimiento (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cliente bigint NOT NULL ,
  id_operacion bigint NOT NULL UNIQUE ,
  puntos bigint NOT NULL CHECK(puntos=1 OR puntos<0),
  created_at timestamptz NOT NULL
);

ALTER TABLE fidelidad_movimiento ENABLE ROW LEVEL SECURITY;

ALTER TABLE cuadre_caja ADD CONSTRAINT fk_cuadre_caja_id_cerrado_por FOREIGN KEY (id_cerrado_por) REFERENCES usuario(id_usuario) ON DELETE RESTRICT;

ALTER TABLE cuadre_caja ADD CONSTRAINT fk_cuadre_caja_id_sucursal FOREIGN KEY (id_sucursal) REFERENCES sucursal(id_sucursal) ON DELETE RESTRICT;

ALTER TABLE servicio_precio_historial ADD CONSTRAINT fk_servicio_precio_historial_id_servicio FOREIGN KEY (id_servicio) REFERENCES servicio(id_servicio) ON DELETE RESTRICT;

ALTER TABLE usuario ADD CONSTRAINT fk_usuario_id_rol FOREIGN KEY (id_rol) REFERENCES rol(id_rol) ON DELETE RESTRICT;

ALTER TABLE gasto ADD CONSTRAINT fk_gasto_id_banco FOREIGN KEY (id_banco) REFERENCES banco(id_banco) ON DELETE RESTRICT;

ALTER TABLE gasto ADD CONSTRAINT fk_gasto_id_metodo_pago FOREIGN KEY (id_metodo_pago) REFERENCES metodo_pago(id_metodo_pago) ON DELETE RESTRICT;

ALTER TABLE gasto ADD CONSTRAINT fk_gasto_id_registrado_por FOREIGN KEY (id_registrado_por) REFERENCES usuario(id_usuario) ON DELETE RESTRICT;

ALTER TABLE gasto ADD CONSTRAINT fk_gasto_id_sucursal FOREIGN KEY (id_sucursal) REFERENCES sucursal(id_sucursal) ON DELETE RESTRICT;

ALTER TABLE gasto ADD CONSTRAINT fk_gasto_id_cuadre_caja FOREIGN KEY (id_cuadre_caja) REFERENCES cuadre_caja(id_cuadre_caja) ON DELETE NO ACTION;

ALTER TABLE cita ADD CONSTRAINT fk_cita_id_creada_por FOREIGN KEY (id_creada_por) REFERENCES usuario(id_usuario) ON DELETE RESTRICT;

ALTER TABLE cita ADD CONSTRAINT fk_cita_id_barbero FOREIGN KEY (id_barbero) REFERENCES usuario(id_usuario) ON DELETE RESTRICT;

ALTER TABLE cita ADD CONSTRAINT fk_cita_id_sucursal FOREIGN KEY (id_sucursal) REFERENCES sucursal(id_sucursal) ON DELETE RESTRICT;

ALTER TABLE cita ADD CONSTRAINT fk_cita_id_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente) ON DELETE RESTRICT;

ALTER TABLE cita ADD CONSTRAINT fk_cita_id_confirmada_por FOREIGN KEY (id_confirmada_por) REFERENCES usuario(id_usuario) ON DELETE RESTRICT;

ALTER TABLE operacion ADD CONSTRAINT fk_operacion_id_cuadre_caja FOREIGN KEY (id_cuadre_caja) REFERENCES cuadre_caja(id_cuadre_caja) ON DELETE RESTRICT;

ALTER TABLE operacion ADD CONSTRAINT fk_operacion_id_registrada_por FOREIGN KEY (id_registrada_por) REFERENCES usuario(id_usuario) ON DELETE RESTRICT;

ALTER TABLE operacion ADD CONSTRAINT fk_operacion_id_barbero FOREIGN KEY (id_barbero) REFERENCES usuario(id_usuario) ON DELETE RESTRICT;

ALTER TABLE operacion ADD CONSTRAINT fk_operacion_id_sucursal FOREIGN KEY (id_sucursal) REFERENCES sucursal(id_sucursal) ON DELETE RESTRICT;

ALTER TABLE operacion ADD CONSTRAINT fk_operacion_id_cita FOREIGN KEY (id_cita) REFERENCES cita(id_cita) ON DELETE RESTRICT;

ALTER TABLE operacion ADD CONSTRAINT fk_operacion_id_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente) ON DELETE RESTRICT;

ALTER TABLE regla_comision ADD CONSTRAINT fk_regla_comision_id_servicio FOREIGN KEY (id_servicio) REFERENCES servicio(id_servicio) ON DELETE RESTRICT;

ALTER TABLE operacion_servicio ADD CONSTRAINT fk_operacion_servicio_id_autorizado_por FOREIGN KEY (id_autorizado_por) REFERENCES usuario(id_usuario) ON DELETE RESTRICT;

ALTER TABLE operacion_servicio ADD CONSTRAINT fk_operacion_servicio_id_regla_comision FOREIGN KEY (id_regla_comision) REFERENCES regla_comision(id_regla_comision) ON DELETE RESTRICT;

ALTER TABLE operacion_servicio ADD CONSTRAINT fk_operacion_servicio_id_motivo_gratuidad FOREIGN KEY (id_motivo_gratuidad) REFERENCES motivo_gratuidad(id_motivo_gratuidad) ON DELETE RESTRICT;

ALTER TABLE operacion_servicio ADD CONSTRAINT fk_operacion_servicio_id_servicio FOREIGN KEY (id_servicio) REFERENCES servicio(id_servicio) ON DELETE RESTRICT;

ALTER TABLE operacion_servicio ADD CONSTRAINT fk_operacion_servicio_id_operacion FOREIGN KEY (id_operacion) REFERENCES operacion(id_operacion) ON DELETE RESTRICT;

ALTER TABLE inventario_sucursal ADD CONSTRAINT fk_inventario_sucursal_id_producto FOREIGN KEY (id_producto) REFERENCES producto(id_producto) ON DELETE RESTRICT;

ALTER TABLE inventario_sucursal ADD CONSTRAINT fk_inventario_sucursal_id_sucursal FOREIGN KEY (id_sucursal) REFERENCES sucursal(id_sucursal) ON DELETE RESTRICT;

ALTER TABLE membresia_plan_servicio ADD CONSTRAINT fk_membresia_plan_servicio_id_servicio FOREIGN KEY (id_servicio) REFERENCES servicio(id_servicio) ON DELETE RESTRICT;

ALTER TABLE membresia_plan_servicio ADD CONSTRAINT fk_membresia_plan_servicio_id_plan_membresia FOREIGN KEY (id_plan_membresia) REFERENCES membresia_plan(id_plan_membresia) ON DELETE RESTRICT;

ALTER TABLE movimiento_inventario ADD CONSTRAINT fk_movimiento_inventario_id_registrado_por FOREIGN KEY (id_registrado_por) REFERENCES usuario(id_usuario) ON DELETE RESTRICT;

ALTER TABLE movimiento_inventario ADD CONSTRAINT fk_movimiento_inventario_id_usuario_responsable FOREIGN KEY (id_usuario_responsable) REFERENCES usuario(id_usuario) ON DELETE RESTRICT;

ALTER TABLE movimiento_inventario ADD CONSTRAINT fk_movimiento_inventario_id_traslado FOREIGN KEY (id_traslado) REFERENCES traslado_inventario(id_traslado) ON DELETE RESTRICT;

ALTER TABLE movimiento_inventario ADD CONSTRAINT fk_movimiento_inventario_id_gasto FOREIGN KEY (id_gasto) REFERENCES gasto(id_gasto) ON DELETE RESTRICT;

ALTER TABLE movimiento_inventario ADD CONSTRAINT fk_movimiento_inventario_id_operacion_producto FOREIGN KEY (id_operacion_producto) REFERENCES operacion_producto(id_operacion_producto) ON DELETE RESTRICT;

ALTER TABLE movimiento_inventario ADD CONSTRAINT fk_movimiento_inventario_id_operacion FOREIGN KEY (id_operacion) REFERENCES operacion(id_operacion) ON DELETE RESTRICT;

ALTER TABLE movimiento_inventario ADD CONSTRAINT fk_movimiento_inventario_id_producto FOREIGN KEY (id_producto) REFERENCES producto(id_producto) ON DELETE RESTRICT;

ALTER TABLE movimiento_inventario ADD CONSTRAINT fk_movimiento_inventario_id_sucursal FOREIGN KEY (id_sucursal) REFERENCES sucursal(id_sucursal) ON DELETE RESTRICT;

ALTER TABLE operacion_producto ADD CONSTRAINT fk_operacion_producto_id_producto FOREIGN KEY (id_producto) REFERENCES producto(id_producto) ON DELETE RESTRICT;

ALTER TABLE operacion_producto ADD CONSTRAINT fk_operacion_producto_id_operacion FOREIGN KEY (id_operacion) REFERENCES operacion(id_operacion) ON DELETE RESTRICT;

ALTER TABLE traslado_inventario ADD CONSTRAINT fk_traslado_inventario_id_responsable FOREIGN KEY (id_responsable) REFERENCES usuario(id_usuario) ON DELETE RESTRICT;

ALTER TABLE traslado_inventario ADD CONSTRAINT fk_traslado_inventario_id_sucursal_destino FOREIGN KEY (id_sucursal_destino) REFERENCES sucursal(id_sucursal) ON DELETE RESTRICT;

ALTER TABLE traslado_inventario ADD CONSTRAINT fk_traslado_inventario_id_sucursal_origen FOREIGN KEY (id_sucursal_origen) REFERENCES sucursal(id_sucursal) ON DELETE RESTRICT;

ALTER TABLE membresia ADD CONSTRAINT fk_membresia_id_operacion_compra FOREIGN KEY (id_operacion_compra) REFERENCES operacion(id_operacion) ON DELETE RESTRICT;

ALTER TABLE membresia ADD CONSTRAINT fk_membresia_id_plan_membresia FOREIGN KEY (id_plan_membresia) REFERENCES membresia_plan(id_plan_membresia) ON DELETE RESTRICT;

ALTER TABLE membresia ADD CONSTRAINT fk_membresia_id_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente) ON DELETE RESTRICT;

ALTER TABLE membresia_consumo ADD CONSTRAINT fk_membresia_consumo_id_operacion_servicio FOREIGN KEY (id_operacion_servicio) REFERENCES operacion_servicio(id_operacion_servicio) ON DELETE RESTRICT;

ALTER TABLE membresia_consumo ADD CONSTRAINT fk_membresia_consumo_id_membresia FOREIGN KEY (id_membresia) REFERENCES membresia(id_membresia) ON DELETE RESTRICT;

ALTER TABLE cita_servicio ADD CONSTRAINT fk_cita_servicio_id_servicio FOREIGN KEY (id_servicio) REFERENCES servicio(id_servicio) ON DELETE RESTRICT;

ALTER TABLE cita_servicio ADD CONSTRAINT fk_cita_servicio_id_cita FOREIGN KEY (id_cita) REFERENCES cita(id_cita) ON DELETE RESTRICT;

ALTER TABLE usuario_sucursal ADD CONSTRAINT fk_usuario_sucursal_id_sucursal FOREIGN KEY (id_sucursal) REFERENCES sucursal(id_sucursal) ON DELETE RESTRICT;

ALTER TABLE usuario_sucursal ADD CONSTRAINT fk_usuario_sucursal_id_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario) ON DELETE RESTRICT;

ALTER TABLE pago ADD CONSTRAINT fk_pago_id_registrado_por FOREIGN KEY (id_registrado_por) REFERENCES usuario(id_usuario) ON DELETE RESTRICT;

ALTER TABLE pago ADD CONSTRAINT fk_pago_id_banco FOREIGN KEY (id_banco) REFERENCES banco(id_banco) ON DELETE RESTRICT;

ALTER TABLE pago ADD CONSTRAINT fk_pago_id_metodo_pago FOREIGN KEY (id_metodo_pago) REFERENCES metodo_pago(id_metodo_pago) ON DELETE RESTRICT;

ALTER TABLE pago ADD CONSTRAINT fk_pago_id_operacion FOREIGN KEY (id_operacion) REFERENCES operacion(id_operacion) ON DELETE RESTRICT;

ALTER TABLE movimiento_caja ADD CONSTRAINT fk_movimiento_caja_id_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario) ON DELETE RESTRICT;

ALTER TABLE movimiento_caja ADD CONSTRAINT fk_movimiento_caja_id_cuadre_caja FOREIGN KEY (id_cuadre_caja) REFERENCES cuadre_caja(id_cuadre_caja) ON DELETE RESTRICT;

ALTER TABLE movimiento_caja ADD CONSTRAINT fk_movimiento_caja_id_gasto FOREIGN KEY (id_gasto) REFERENCES gasto(id_gasto) ON DELETE RESTRICT;

ALTER TABLE movimiento_caja ADD CONSTRAINT fk_movimiento_caja_id_pago FOREIGN KEY (id_pago) REFERENCES pago(id_pago) ON DELETE RESTRICT;

ALTER TABLE movimiento_caja ADD CONSTRAINT fk_movimiento_caja_id_sucursal FOREIGN KEY (id_sucursal) REFERENCES sucursal(id_sucursal) ON DELETE RESTRICT;

ALTER TABLE bitacora_auditoria ADD CONSTRAINT fk_bitacora_auditoria_id_sucursal FOREIGN KEY (id_sucursal) REFERENCES sucursal(id_sucursal) ON DELETE RESTRICT;

ALTER TABLE bitacora_auditoria ADD CONSTRAINT fk_bitacora_auditoria_id_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario) ON DELETE RESTRICT;

ALTER TABLE cliente_nota ADD CONSTRAINT fk_cliente_nota_id_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario) ON DELETE NO ACTION;

ALTER TABLE cliente_nota ADD CONSTRAINT fk_cliente_nota_id_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente) ON DELETE NO ACTION;

ALTER TABLE beneficio_cumpleanos ADD CONSTRAINT fk_beneficio_cumpleanos_id_operacion FOREIGN KEY (id_operacion) REFERENCES operacion(id_operacion) ON DELETE NO ACTION;

ALTER TABLE beneficio_cumpleanos ADD CONSTRAINT fk_beneficio_cumpleanos_id_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente) ON DELETE NO ACTION;

ALTER TABLE solicitud_idempotente ADD CONSTRAINT fk_solicitud_idempotente_id_sucursal FOREIGN KEY (id_sucursal) REFERENCES sucursal(id_sucursal) ON DELETE NO ACTION;

ALTER TABLE solicitud_idempotente ADD CONSTRAINT fk_solicitud_idempotente_id_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario) ON DELETE NO ACTION;

ALTER TABLE membresia_servicio ADD CONSTRAINT fk_membresia_servicio_id_servicio FOREIGN KEY (id_servicio) REFERENCES servicio(id_servicio) ON DELETE NO ACTION;

ALTER TABLE membresia_servicio ADD CONSTRAINT fk_membresia_servicio_id_membresia FOREIGN KEY (id_membresia) REFERENCES membresia(id_membresia) ON DELETE NO ACTION;

ALTER TABLE fidelidad_movimiento ADD CONSTRAINT fk_fidelidad_movimiento_id_operacion FOREIGN KEY (id_operacion) REFERENCES operacion(id_operacion) ON DELETE RESTRICT;

ALTER TABLE fidelidad_movimiento ADD CONSTRAINT fk_fidelidad_movimiento_id_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente) ON DELETE RESTRICT;

CREATE INDEX ix_cuadre_caja_id_sucursal ON cuadre_caja(id_sucursal);

CREATE INDEX ix_cuadre_caja_id_cerrado_por ON cuadre_caja(id_cerrado_por);

CREATE INDEX ix_servicio_precio_historial_id_servicio ON servicio_precio_historial(id_servicio);

CREATE INDEX ix_usuario_id_rol ON usuario(id_rol);

CREATE INDEX ix_gasto_id_sucursal ON gasto(id_sucursal);

CREATE INDEX ix_gasto_id_registrado_por ON gasto(id_registrado_por);

CREATE INDEX ix_gasto_id_metodo_pago ON gasto(id_metodo_pago);

CREATE INDEX ix_gasto_id_banco ON gasto(id_banco);

CREATE INDEX ix_cita_id_cliente ON cita(id_cliente);

CREATE INDEX ix_cita_id_sucursal ON cita(id_sucursal);

CREATE INDEX ix_cita_id_barbero ON cita(id_barbero);

CREATE INDEX ix_cita_id_creada_por ON cita(id_creada_por);

CREATE INDEX ix_operacion_id_cliente ON operacion(id_cliente);

CREATE INDEX ix_operacion_id_cita ON operacion(id_cita);

CREATE INDEX ix_operacion_id_sucursal ON operacion(id_sucursal);

CREATE INDEX ix_operacion_id_barbero ON operacion(id_barbero);

CREATE INDEX ix_operacion_id_registrada_por ON operacion(id_registrada_por);

CREATE INDEX ix_operacion_id_cuadre_caja ON operacion(id_cuadre_caja);

CREATE INDEX ix_regla_comision_id_servicio ON regla_comision(id_servicio);

CREATE INDEX ix_operacion_servicio_id_operacion ON operacion_servicio(id_operacion);

CREATE INDEX ix_operacion_servicio_id_servicio ON operacion_servicio(id_servicio);

CREATE INDEX ix_operacion_servicio_id_motivo_gratuidad ON operacion_servicio(id_motivo_gratuidad);

CREATE INDEX ix_operacion_servicio_id_regla_comision ON operacion_servicio(id_regla_comision);

CREATE INDEX ix_operacion_servicio_id_autorizado_por ON operacion_servicio(id_autorizado_por);

CREATE INDEX ix_inventario_sucursal_id_sucursal ON inventario_sucursal(id_sucursal);

CREATE INDEX ix_inventario_sucursal_id_producto ON inventario_sucursal(id_producto);

CREATE INDEX ix_membresia_plan_servicio_id_plan_membresia ON membresia_plan_servicio(id_plan_membresia);

CREATE INDEX ix_membresia_plan_servicio_id_servicio ON membresia_plan_servicio(id_servicio);

CREATE INDEX ix_movimiento_inventario_id_sucursal ON movimiento_inventario(id_sucursal);

CREATE INDEX ix_movimiento_inventario_id_producto ON movimiento_inventario(id_producto);

CREATE INDEX ix_movimiento_inventario_id_operacion ON movimiento_inventario(id_operacion);

CREATE INDEX ix_movimiento_inventario_id_operacion_producto ON movimiento_inventario(id_operacion_producto);

CREATE INDEX ix_movimiento_inventario_id_gasto ON movimiento_inventario(id_gasto);

CREATE INDEX ix_movimiento_inventario_id_traslado ON movimiento_inventario(id_traslado);

CREATE INDEX ix_movimiento_inventario_id_usuario_responsable ON movimiento_inventario(id_usuario_responsable);

CREATE INDEX ix_movimiento_inventario_id_registrado_por ON movimiento_inventario(id_registrado_por);

CREATE INDEX ix_operacion_producto_id_operacion ON operacion_producto(id_operacion);

CREATE INDEX ix_operacion_producto_id_producto ON operacion_producto(id_producto);

CREATE INDEX ix_traslado_inventario_id_sucursal_origen ON traslado_inventario(id_sucursal_origen);

CREATE INDEX ix_traslado_inventario_id_sucursal_destino ON traslado_inventario(id_sucursal_destino);

CREATE INDEX ix_traslado_inventario_id_responsable ON traslado_inventario(id_responsable);

CREATE INDEX ix_membresia_id_cliente ON membresia(id_cliente);

CREATE INDEX ix_membresia_id_plan_membresia ON membresia(id_plan_membresia);

CREATE INDEX ix_membresia_id_operacion_compra ON membresia(id_operacion_compra);

CREATE INDEX ix_membresia_consumo_id_membresia ON membresia_consumo(id_membresia);

CREATE INDEX ix_membresia_consumo_id_operacion_servicio ON membresia_consumo(id_operacion_servicio);

CREATE INDEX ix_cita_servicio_id_cita ON cita_servicio(id_cita);

CREATE INDEX ix_cita_servicio_id_servicio ON cita_servicio(id_servicio);

CREATE INDEX ix_usuario_sucursal_id_usuario ON usuario_sucursal(id_usuario);

CREATE INDEX ix_usuario_sucursal_id_sucursal ON usuario_sucursal(id_sucursal);

CREATE INDEX ix_pago_id_operacion ON pago(id_operacion);

CREATE INDEX ix_pago_id_metodo_pago ON pago(id_metodo_pago);

CREATE INDEX ix_pago_id_banco ON pago(id_banco);

CREATE INDEX ix_pago_id_registrado_por ON pago(id_registrado_por);

CREATE INDEX ix_movimiento_caja_id_sucursal ON movimiento_caja(id_sucursal);

CREATE INDEX ix_movimiento_caja_id_pago ON movimiento_caja(id_pago);

CREATE INDEX ix_movimiento_caja_id_gasto ON movimiento_caja(id_gasto);

CREATE INDEX ix_movimiento_caja_id_cuadre_caja ON movimiento_caja(id_cuadre_caja);

CREATE INDEX ix_movimiento_caja_id_usuario ON movimiento_caja(id_usuario);

CREATE INDEX ix_bitacora_auditoria_id_usuario ON bitacora_auditoria(id_usuario);

CREATE INDEX ix_bitacora_auditoria_id_sucursal ON bitacora_auditoria(id_sucursal);

CREATE INDEX ix_bitacora_auditoria_id_registro ON bitacora_auditoria(id_registro);

CREATE INDEX ix_cliente_nombre ON cliente(nombre_completo );

CREATE INDEX ix_cliente_telefono ON cliente(telefono);

CREATE INDEX ix_operacion_fecha ON operacion(id_sucursal,fecha_hora);

CREATE UNIQUE INDEX ux_precio_vigente ON servicio_precio_historial(id_servicio) WHERE vigencia_hasta IS NULL;

CREATE INDEX ix_gasto_cuadre ON gasto(id_sucursal,id_cuadre_caja);

CREATE INDEX ix_caja_pendiente ON movimiento_caja(id_sucursal,id_cuadre_caja);

CREATE INDEX ix_cita_horario ON cita(id_barbero,estado,fecha_hora);

CREATE INDEX ix_fidelidad_cliente ON fidelidad_movimiento(id_cliente);

ALTER TABLE cita ADD CONSTRAINT cita_estado_valido CHECK (estado IN ('PENDIENTE','ATENDIDA','CANCELADA'));

ALTER TABLE cita ADD CONSTRAINT cita_confirmacion_consistente CHECK ((estado='ATENDIDA') = (confirmada_at IS NOT NULL AND id_confirmada_por IS NOT NULL));

CREATE INDEX ix_cita_confirmada_por ON cita(id_confirmada_por);

CREATE INDEX ix_membresia_servicio_servicio ON membresia_servicio(id_servicio);

CREATE INDEX ix_cliente_nota_cliente ON cliente_nota(id_cliente);

CREATE INDEX ix_cliente_nota_usuario ON cliente_nota(id_usuario);

CREATE INDEX ix_solicitud_usuario ON solicitud_idempotente(id_usuario);

CREATE INDEX ix_solicitud_sucursal ON solicitud_idempotente(id_sucursal);

ALTER TABLE cliente ADD CONSTRAINT cliente_datos CHECK (length(trim(nombre_completo)) BETWEEN 3 AND 150 AND length(regexp_replace(telefono,'[^0-9]','','g')) BETWEEN 8 AND 15);

ALTER TABLE regla_comision ADD CONSTRAINT comision_valida CHECK (tipo_calculo IN ('FIJO','PORCENTAJE') AND (tipo_calculo<>'PORCENTAJE' OR valor<=10000));

REVOKE ALL ON ALL TABLES IN SCHEMA valhalla_private FROM PUBLIC, anon, authenticated;

REVOKE ALL ON ALL SEQUENCES IN SCHEMA valhalla_private FROM PUBLIC, anon, authenticated;
