"""Genera el modelo PostgreSQL a partir del esquema SQLite verificado del DER.
Solo construye archivos locales; nunca se conecta a una base remota.
"""
from pathlib import Path
import re
import sqlite3

root = Path(__file__).resolve().parents[1]
db = sqlite3.connect(':memory:')
for name in ['schema.sql', 'migrations/002_revision.sql', 'migrations/003_central.sql', 'migrations/004_recuperacion_citas.sql']:
    db.executescript((root / 'assets' / name).read_text())
skip = {'credencial_usuario', 'sesion_acceso', 'intento_acceso', 'recuperacion_password'}
tables = [(n, s) for n, s in db.execute("select name, sql from sqlite_master where type='table'") if n not in skip]

def split_columns(text):
    out, start, depth, quote = [], 0, 0, False
    for i, c in enumerate(text):
        if c == "'": quote = not quote
        if not quote:
            if c == '(': depth += 1
            elif c == ')': depth -= 1
            elif c == ',' and depth == 0:
                out.append(text[start:i].strip()); start = i + 1
    out.append(text[start:].strip())
    return out

sql = ['-- VALHALLA 0.3 · PostgreSQL / Supabase. Importes en centavos; stock en milésimas.',
       '-- Ejecutar 01, 02, 03 en ese orden; INSTALAR_VALHALLA.sql los reúne en una transacción.',
       'CREATE SCHEMA IF NOT EXISTS valhalla_private;',
       'REVOKE ALL ON SCHEMA valhalla_private FROM PUBLIC, anon, authenticated;',
       'SET LOCAL search_path = valhalla_private, pg_catalog;']
foreign = []
for name, original in tables:
    cols = []
    body = original[original.index('(')+1:original.rindex(')')]
    for col in split_columns(body):
        if col.upper().startswith('FOREIGN KEY'): continue
        col = re.sub(r"REFERENCES\s+\w+\s*\([^)]*\)(?:\s+ON DELETE\s+\w+)?", '', col, flags=re.I)
        col = col.replace("(strftime('%Y-%m-%dT%H:%M:%fZ','now'))", 'now()')
        col = re.sub(r'\bINTEGER PRIMARY KEY\b', 'bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', col, flags=re.I)
        col = re.sub(r'\bINTEGER\b', 'bigint', col, flags=re.I)
        col = col.replace('COLLATE NOCASE', '')
        col = re.sub(r'\b(fecha_nacimiento) TEXT\b', r'\1 date', col)
        col = re.sub(r'\b(\w+_at|fecha_\w+|vigencia_\w+|periodo_\w+) TEXT\b', r'\1 timestamptz', col)
        if name == 'usuario' and col.startswith('firebase_uid '):
            col = 'auth_uid uuid UNIQUE REFERENCES auth.users(id) ON DELETE RESTRICT'
        cols.append(col)
    if name == 'usuario':
        cols += ['correo text NOT NULL UNIQUE CHECK (correo = lower(trim(correo)))',
                 "acceso_desde timestamptz NOT NULL DEFAULT '-infinity'"]
    sql.append(f'CREATE TABLE {name} (\n  ' + ',\n  '.join(cols) + '\n);')
    sql.append(f'ALTER TABLE {name} ENABLE ROW LEVEL SECURITY;')
    for fk in db.execute(f'PRAGMA foreign_key_list("{name}")'):
        _, _, target, field, target_field, _, delete, _ = fk
        if target in skip: continue
        foreign.append(f'ALTER TABLE {name} ADD CONSTRAINT fk_{name}_{field} FOREIGN KEY ({field}) REFERENCES {target}({target_field}) ON DELETE {delete};')
sql += foreign
for name, table, index in db.execute("select name,tbl_name,sql from sqlite_master where type='index' and sql is not null"):
    if table not in skip:
        sql.append(index.replace('COLLATE NOCASE', '') + ';')
sql += [
    "ALTER TABLE cita ADD CONSTRAINT cita_estado_valido CHECK (estado IN ('PENDIENTE','ATENDIDA','CANCELADA'));",
    "ALTER TABLE cita ADD CONSTRAINT cita_confirmacion_consistente CHECK ((estado='ATENDIDA') = (confirmada_at IS NOT NULL AND id_confirmada_por IS NOT NULL));",
    "CREATE INDEX ix_cita_confirmada_por ON cita(id_confirmada_por);",
    "CREATE INDEX ix_membresia_servicio_servicio ON membresia_servicio(id_servicio);",
    "CREATE INDEX ix_cliente_nota_cliente ON cliente_nota(id_cliente);",
    "CREATE INDEX ix_cliente_nota_usuario ON cliente_nota(id_usuario);",
    "CREATE INDEX ix_solicitud_usuario ON solicitud_idempotente(id_usuario);",
    "CREATE INDEX ix_solicitud_sucursal ON solicitud_idempotente(id_sucursal);",
    "ALTER TABLE cliente ADD CONSTRAINT cliente_datos CHECK (length(trim(nombre_completo)) BETWEEN 3 AND 150 AND length(regexp_replace(telefono,'[^0-9]','','g')) BETWEEN 8 AND 15);",
    "ALTER TABLE regla_comision ADD CONSTRAINT comision_valida CHECK (tipo_calculo IN ('FIJO','PORCENTAJE') AND (tipo_calculo<>'PORCENTAJE' OR valor<=10000));",
    "REVOKE ALL ON ALL TABLES IN SCHEMA valhalla_private FROM PUBLIC, anon, authenticated;",
    "REVOKE ALL ON ALL SEQUENCES IN SCHEMA valhalla_private FROM PUBLIC, anon, authenticated;",
]
out = root / 'supabase' / 'sql'
out.mkdir(parents=True, exist_ok=True)
(out / '01_modelo.sql').write_text('\n\n'.join(sql) + '\n')
print(f'Modelo exportado: {len(tables)} tablas, {len(foreign)} relaciones del DER.')
